name: Java CI/CD with Gradle

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle Wrapper
      run: chmod +x ./gradlew; ./gradlew build

    - name: Upload artifact (JAR file)
      uses: actions/upload-artifact@v4
      with:
        name: tp-jar
        path: build/libs/tp-article-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      
    steps:
    
    - name: Download artifact (JAR file)
      uses: actions/download-artifact@v4
      with:
        name: tp-jar  # Le nom de l'artefact que nous avons upload√© dans le job build
        
    - name: Publish to server
      uses: appleboy/scp-action@master
      with:
        host: 138.68.128.114
        username: root
        password: cHocolatin13e
        source: "/home/runner/work/TP_R35_Q06/TP_R35_Q06/tp-article-0.0.1-SNAPSHOT.jar"
        target: /home/app/
